### ISSUE TITLE
Improve Dashboard Person Cards

### ISSUE THREAD

**Issue by pjames27** [pfw13/codex-insurance-fullstack#15]
On the Dashboard, the Person cards shouldn't show the person id directly.
The name, dob, date, immunocompromised status, and _maybe_ some more friendly id (e.g. "Person 1") should be visible.

Later, may want to include dependent status or other relationships.

**Comment by alissav30** [comment]
done in latest commit! created new PR for adding more info to the dataset on the backend so that the frontend dataset can pull from it
